# Human Tasks:
# 1. Verify Kubernetes cluster version is 1.19+ before deployment
# 2. Ensure Helm v3.0+ is installed on deployment environment
# 3. Validate ingress-nginx repository is accessible
# 4. Confirm cert-manager repository is accessible
# 5. Review maintainer contact information is current

# Addresses requirement: Web Application Deployment (2.1 High-Level Architecture Overview/Client Layer)
# Defines Helm chart for deploying React Native Web application with high availability
apiVersion: v2
name: mint-replica-web
description: Helm chart for Mint Replica Lite web application frontend with high availability and secure ingress
type: application
version: 1.0.0
appVersion: 1.0.0

# Addresses requirement: Infrastructure as Code (2.5 Infrastructure Architecture/2.5.2 Deployment Architecture)
# Defines required chart dependencies for secure ingress and certificate management
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: cert-manager
    version: 1.12.0
    repository: https://charts.jetstack.io
    condition: ingress.tls.enabled

# Chart metadata and maintainer information
maintainers:
  - name: DevOps Team
    email: devops@mintreplicalite.com

keywords:
  - web
  - frontend
  - react-native
  - mint-replica-lite
  - high-availability
  - secure-ingress

home: https://github.com/mintreplicalite/web
sources:
  - https://github.com/mintreplicalite/web

# Addresses requirement: Containerization (2.5.2 Deployment Architecture)
# Provides metadata for chart deployment and compatibility
annotations:
  artifacthub.io/changes: "Initial release of Mint Replica Lite web frontend chart"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: "Requires Kubernetes 1.19+ and Helm 3.0+"
  artifacthub.io/license: "MIT"